### ISSUE TITLE
Usage licence

### ISSUE THREAD

**Issue by Mayeu** [CommonsDev/kanban#2]
Hello,

I have a question about this code re-usability, there is no license, or right waiver in this repository, and sadly, that means in lot of country that the default right will be the Authors' rights, which in a lot of case prevent any re-usability or modification.

Can you clarify the license used in this project?

Thank you.

**Comment by glibersat** [comment]
Hi @Mayeu,

You're right, sorry, we forgot to add the `LICENSE` file! It's released under AGPLv3, I'll add a file soon.
If you need assistance when digging the code, feel free to open an issue.

Cheers,

Guillaume

**Comment by Mayeu** [comment]
:+1:

**Comment by glibersat** [comment]
I've added the file! thanks for pointing that problem.

**Comment by Mayeu** [comment]
Thank you :)
